// LOGIN ACTIONS
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';

// REDIRECT ACTIONS
export const REDIRECT_RQUESTED = 'REDIRECT_RQUESTED';
export const REDIRECT_WITH_PARAMS_RQUESTED = 'REDIRECT_WITH_PARAMS_RQUESTED';

//SIGN UP
export const FETCH_USER_SIGNUP_REQUESTED = 'FETCH_USER_SIGNUP_REQUESTED';
export const FETCH_USER_SIGNUP_SUCCESS = 'FETCH_USER_SIGNUP_SUCCESS';
export const FETCH_USER_SIGNUP_FAILED = 'FETCH_USER_SIGNUP_FAILED';

//FORGET PASSWORD
export const FETCH_FORGET_PASSWORD_REQUESTED =
  'FETCH_FORGET_PASSWORD_REQUESTED';
export const FETCH_FORGET_PASSWORD_SUCCESS = 'FETCH_FORGET_PASSWORD_SUCCESS';
export const FETCH_FORGET_PASSWORD_FAILED = 'FETCH_FORGET_PASSWORD_FAILED';

//RESET PASSWORD
export const FETCH_RESET_PASSWORD_REQUESTED = 'FETCH_RESET_PASSWORD_REQUESTED';
export const FETCH_RESET_PASSWORD_SUCCESS = 'FETCH_RESET_PASSWORD_SUCCESS';
export const FETCH_RESET_PASSWORD_FAILED = 'FETCH_RESET_PASSWORD_FAILED';

// FIND STORE
export const FETCH_FIND_STORE_REQUESTED = 'FETCH_FIND_STORE_REQUESTED';
export const FETCH_FIND_STORE_SUCCESS = 'FETCH_FIND_STORE_SUCCESS';
export const FETCH_FIND_STORE_FAILED = 'FETCH_FIND_STORE_FAILED';

// MENU ITEM

export const FETCH_MENU_ITEMS_REQUESTED = 'FETCH_MENU_ITEMS_REQUESTED';
export const FETCH_MENU_ITEMS_SUCCESS = 'FETCH_MENU_ITEMS_SUCCESS';
export const FETCH_MENU_ITEMS_FAILED = 'FETCH_MENU_ITEMS_FAILED';

//SPECIFY YOUR DISH
export const FETCH_SPECIFY_DISH_REQUESTED = 'FETCH_SPECIFY_DISH_REQUESTED';
export const FETCH_SPECIFY_DISH_SUCCESS = 'FETCH_SPECIFY_DISH_SUCCESS';
export const FETCH_SPECIFY_DISH_FAILED = 'FETCH_SPECIFY_DISH_FAILED';

//ADD TO CART
export const ADD_TO_CART_REQUESTED = 'ADD_TO_CART_REQUESTED';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';
